# typed: false
# frozen_string_literal: true

# Homebrew formula for the babysit CLI (`bbs`).
#
# Delivers the compiled `bbs` multicall binary. All core bins are now Go,
# reachable as `bbs <sub>` (ticket, config, secrets, upgrade, design,
# dashboard, autopilot, foreman), plus the `bbs-config` / `bbs-env` argv0
# aliases. It does NOT install the
# babysit skill pack (skills, workflows, DESIGN.md/CSV data), which
# comes from git clone + go run ./cmd/bbs setup.
#
# Generated by scripts/gen-formula.sh; the release workflow regenerates it with
# real checksums on each tag. Do not hand-edit the sha256 values.
class Bbs < Formula
  desc "Babysit CLI — Go multicall for config, env, slug, ticket, and more"
  homepage "https://github.com/lohi-ai/babysit"
  version "1.93.7"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_arm64.tar.gz"
      sha256 "f88548ea2b33badfad3c16a2029fc8c6b64495506a0dbbc9aec6f5dab3251969"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_amd64.tar.gz"
      sha256 "f4e13ec39a12c9c900a5214139ea68533097b29944518519c0cc96b91f8f708d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_arm64.tar.gz"
      sha256 "fb2f248e11a6a7e6557efaf20dc9eabb910c55d84e98f29add5d7bb56d40d6ab"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_amd64.tar.gz"
      sha256 "3f45bc8ee693e300c6d2eb737479a47a93e50ca02318181251fe4ede9d63ad97"
    end
  end

  def install
    bin.install "bbs"
    # Multicall aliases: dispatch keys on argv0, so bbs-<name> runs "bbs <name>".
    # Only subcommands the CLI registers today are aliased.
    bin.install_symlink bin/"bbs" => "bbs-config"
    bin.install_symlink bin/"bbs" => "bbs-env"
  end

  test do
    assert_match "babysit CLI", shell_output("#{bin}/bbs --help")
    assert_match "config", shell_output("#{bin}/bbs-config --help")
  end
end
