# typed: false
# frozen_string_literal: true

# Homebrew formula for the babysit CLI (`bbs`).
#
# Delivers the compiled `bbs` multicall binary. All core bins are now Go,
# reachable as `bbs <sub>` (ticket, config, secrets, upgrade, design,
# dashboard, autopilot, foreman), plus the `bbs-config` / `bbs-env` argv0
# aliases. It does NOT install the
# babysit skill pack (skills, workflows, DESIGN.md/CSV data), which
# comes from git clone + bin/setup-skills.
#
# Generated by scripts/gen-formula.sh; the release workflow regenerates it with
# real checksums on each tag. Do not hand-edit the sha256 values.
class Bbs < Formula
  desc "Babysit CLI — Go multicall for config, env, slug, ticket, and more"
  homepage "https://github.com/lohi-ai/babysit"
  version "1.93.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_arm64.tar.gz"
      sha256 "443cf64b1d1986d6057e1af02154e73688ba6a3fbb569482b3f0b5181e81cbff"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_amd64.tar.gz"
      sha256 "5739c47a7cb9ea5049712a91c84f3d51cdd671f58ccc55ef028b3fd683e04fc4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_arm64.tar.gz"
      sha256 "e0d773e616ee8ecf404492be136ef92732a1fb057fbaf82c186fc8ccf28b971a"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_amd64.tar.gz"
      sha256 "b43d41d7a9c9123f9a3a66730db48acbe352a271e1ed7b14d66659eb35f25e6e"
    end
  end

  def install
    bin.install "bbs"
    # Multicall aliases: dispatch keys on argv0, so bbs-<name> runs "bbs <name>".
    # Only subcommands the CLI registers today are aliased.
    bin.install_symlink bin/"bbs" => "bbs-config"
    bin.install_symlink bin/"bbs" => "bbs-env"
  end

  test do
    assert_match "babysit CLI", shell_output("#{bin}/bbs --help")
    assert_match "config", shell_output("#{bin}/bbs-config --help")
  end
end
