# typed: false
# frozen_string_literal: true

# Homebrew formula for the babysit CLI (`bbs`).
#
# Delivers the compiled `bbs` multicall binary. All core bins are now Go,
# reachable as `bbs <sub>` (ticket, config, secrets, upgrade, design,
# dashboard, autopilot, foreman), plus the `bbs-config` / `bbs-env` argv0
# aliases. It does NOT install the
# babysit skill pack (skills, workflows, DESIGN.md/CSV data), which
# comes from git clone + go run ./cmd/bbs setup.
#
# Generated by scripts/gen-formula.sh; the release workflow regenerates it with
# real checksums on each tag. Do not hand-edit the sha256 values.
class Bbs < Formula
  desc "Babysit CLI — Go multicall for config, env, slug, ticket, and more"
  homepage "https://github.com/lohi-ai/babysit"
  version "1.93.11"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_arm64.tar.gz"
      sha256 "0855c6ef9b8197d19aaf0290ab27182d93e1aff8eb251df36cd75f8e65b94966"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_darwin_amd64.tar.gz"
      sha256 "210a6696ff5cd8e63853c6e238765fccc32f5a1bc4e236fa57c5ca9ce9d704d8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_arm64.tar.gz"
      sha256 "426d8e63f1409e1662f3a36934da5ee4a46fd9ae5775f9c08d0a613d7590e0ef"
    end
    on_intel do
      url "https://github.com/lohi-ai/babysit/releases/download/v#{version}/bbs_#{version}_linux_amd64.tar.gz"
      sha256 "da0b73bff611eadfc6ed49665a5274a6e5f2a6e8263fd7205d757cbea847db15"
    end
  end

  def install
    bin.install "bbs"
    # Multicall aliases: dispatch keys on argv0, so bbs-<name> runs "bbs <name>".
    # Only subcommands the CLI registers today are aliased.
    bin.install_symlink bin/"bbs" => "bbs-config"
    bin.install_symlink bin/"bbs" => "bbs-env"
  end

  test do
    assert_match "babysit CLI", shell_output("#{bin}/bbs --help")
    assert_match "config", shell_output("#{bin}/bbs-config --help")
  end
end
